FROM openknowledge/ckan-base:2.9-py2

MAINTAINER Open Knowledge Foundation <info@okfn.org>

ENV APP_DIR=/srv/app
ENV SRC_EXTENSIONS_DIR=/srv/app/src_extensions

# Install packages needed by the dev requirements
RUN apk add --no-cache libffi-dev

# Install CKAN dev requirements
RUN pip2 install -r https://raw.githubusercontent.com/ckan/ckan/${GIT_BRANCH}/dev-requirements.txt

# Create folder for local extensions sources
RUN mkdir $SRC_EXTENSIONS_DIR

COPY 2.9/setup/start_ckan_development-py2.sh ${APP_DIR}


CMD ["/srv/app/start_ckan_development-py2.sh"]
