name: 'Remove untagged images'

on:
  schedule:
    - cron: '0 20 * * *' # runs daily
  workflow_dispatch: # allows for manual invocation

env:
  GAR_ZONE: europe-southwest1
  GAR_REPO_NAME: docker-ckan-images
  G_PROJECT_ID: oki-cloud
  G_SERVICE_ACCOUT: sa-gh-action-registry

jobs:
  gcr-cleaner:
    runs-on: 'ubuntu-latest'
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/3555635429/locations/global/workloadIdentityPools/gh-action-registry-pool/providers/gh-provider
          service_account: ${{ env.G_SERVICE_ACCOUT }}@${{ env.G_PROJECT_ID }}.iam.gserviceaccount.com
          # Wait for all builds ...
          access_token_lifetime: 3600s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GAR_ZONE }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      # customize based on the gcr-cleaner flags
      - uses: 'docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
        with:
          args: >-
            -repo=${{ env.GAR_ZONE }}-docker.pkg.dev/${{ env.G_PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/openknowledge/ckan-base
            -repo=${{ env.GAR_ZONE }}-docker.pkg.dev/${{ env.G_PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/openknowledge/ckan-dev
            -grace=48h
